# This is for an MSYS2 on Windows build
# For now, llf has to be built to run in 32 bit mode.

HOST_MACH = -m32
DELIM = '
PiOS32 = 0
LINUX = 1
MSYS2 = 1
MINGW = 0
EXTRA_DEFINES = -DMSYS2 -DWIN32
EXTRA_CHKS =
DBG = 
OPT = -O2
CC = gcc
ECHO = /bin/echo -e
RM = rm -f
RMDIR = rm -rf

include Makefile.common


