# This is for a generic Linux build
# For now, llf has to be built to run in 32 bit mode.

HOST_MACH = 
DELIM = '
PiOS32 = 0
LINUX = 1
MSYS2 = 0
MINGW = 0
EXTRA_DEFINES = -DM_UNIX 
EXTRA_CHKS = #-std=c99
DBG = #-g
OPT = -O2
CC = gcc
ECHO = /bin/echo -e
RM = rm -f
RMDIR = rm -rf

include Makefile.common
